### ISSUE TITLE
Si la base de données est vide, l'app front ne se lance pas

### ISSUE THREAD

**Issue by AudreyBramy** [etalab/radar-tech-frontend#17]
Lorsqu'on déploie pour la première fois, la base de données est vide.
Ça génère une erreur lors du lancement de l'app. 

`error Building static HTML failed for path "/resultats/"
WebpackError: TypeError: Reduce of empty array with no initial value`

**Comment by Balaiseee** [comment]
Dans le fichier `resultats.tsx`, la ligne 81 pose problème au déploiement :

`{results.length - gender_flat.map(e => e.n).reduce((a, b) => a + b)}` : `TypeError: reduce of empty array with no initial value`

Cela doit être dû à l'absence de valeur initiale.

Suggestion d'une potentielle solution :

`{results.length - gender_flat.map(e => e.n).reduce((a, b) => a + b, 0)}`

[Source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Reduce_of_empty_array_with_no_initial_value)

**Comment by basilesimon** [comment]
@Balaiseee Merci ! L'issue étant toujours active, je t'invite à enlever (commenter) ces pans de la page de résultats. Cette page devra de toute façon être exclue des déploiements avant la publications finale en novembre.

**Comment by Balaiseee** [comment]
> @Balaiseee Merci ! L'issue étant toujours active, je t'invite à enlever (commenter) ces pans de la page de résultats. Cette page devra de toute façon être exclue des déploiements avant la publications finale en novembre.

J'ai fait une pull request en apportant cette solution : https://github.com/etalab/radar-tech-frontend/pull/20

> Dans le fichier `resultats.tsx`, la ligne 81 pose problème au déploiement :
> 
> `{results.length - gender_flat.map(e => e.n).reduce((a, b) => a + b)}` : `TypeError: reduce of empty array with no initial value`
> 
> Cela doit être dû à l'absence de valeur initiale.
> 
> Suggestion d'une potentielle solution :
> 
> `{results.length - gender_flat.map(e => e.n).reduce((a, b) => a + b, 0)}`
> 
> [Source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Reduce_of_empty_array_with_no_initial_value)

Elle fonctionne (testée avec Dokku) ! :)
